SELECT * FROM filmydvd.dvd;CREATE TABLE `dvd` (
  `DVD_TITLE` varchar(50) DEFAULT NULL,
  `DVD_STAR_NAME` varchar(50) DEFAULT NULL,
  `DVD_COSTAR_NAME` varchar(50) DEFAULT NULL,
  `DVD_YEAR` varchar(50) DEFAULT NULL,
  `DVD_GENRE` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;